### ISSUE TITLE
Any readme on how to use this in meteor

### ISSUE THREAD

**Issue by joshua1** [aruntk/polymer#1]
Any?

**Comment by aruntk** [comment]
Package will automatically add necessary files in your project director. You can use the official guide [polymer docs](https://www.polymer-project.org/docs/polymer/polymer.html) . For eg. adding raised paper button element - `<paper-button raised>raised button</paper-button>` 

To include paper elements add `<link rel="import" href="/bower_components/paper-elements/paper-elements.html">` inside head
