### ISSUE TITLE
Please consider deprecating the package

### ISSUE THREAD

**Issue by dandv** [aruntk/polymer#2]
This package is 2+ years old and probably no longer works with Meteor 1.0+. I see you're working on a much newer and more frequently maintained alternative, https://atmospherejs.com/mwc/synthesis.

You can hide the old package from Atmosphere searches while letting dependent packages and apps use it with the following command:

```
meteor admin set-unmigrated <package:name>
```

**Comment by aruntk** [comment]
@dandv Thank you for notifying. I'll hide this package and continue developing synthesis and other mwc packages. Here is a boilerplate app https://github.com/aruntk/kickstart-meteor-polymer-with-app-route to start your meteor polymer project.
